core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('', include('profiles.urls', namespace='profile')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

] 
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.db.models.query import NamedValuesListIterable
from django.urls import path, re_path
from django.utils.regex_helper import ESCAPE_MAPPINGS
from store import views

app_name='store'
urlpatterns = [
    path('',views.index, name='index'),
    path('product-detail/<int:id>/', views.productDetail, name='product-detail'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    #('login/',views.loginView, name='login'),
    path('category/', views.category, name='category'),
    path('register/', views.registerUser, name='register'),
    #path('add-to-cart/<int:id>/', views.addToCart, name='add_to_cart')
    path('logout/', views.logout, name='logout')
]
 

store/models.py
from django.db.models.fields.related import ManyToManyField
from profiles.models import Profile
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
 

# Create your models here.
#=======================Peofile==================================================================================================================

        
#===================Categories====================================
class Category(models.Model):
    name = models.CharField(
        max_length=100, db_index=True, null=True, blank=True)
    image = models.ImageField(blank=True)
   # slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = 'Catégories'

    @property
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=''
        return url
    @property
    def imageCat(self):
        try:
            if self.image.url !='':
                image=self.image.url
        except:
            image='store/img/dkandroid.png'
        return image

    def __str__(self):
        return self.name

#=========================Product===========================================
class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    category = models.ForeignKey(Category, verbose_name='Catégorie', on_delete=models.RESTRICT, null=True, blank=True)
    # slug = models.SlugField( unique=True, max_length=200)
    price = models.IntegerField( verbose_name='Prix réduit')
    oldPrice = models.IntegerField(verbose_name='Prix Normal' )
    description = models.TextField(blank=True)
    image = models.ImageField(blank=True, null=True)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    in_stock = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Produits'
        ordering = ('-added_at',)
    @property
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=''
        return url
    @property
    def CategoryExcept(self):
        try:
            
            categoryName = self.category.name
        except:
            categoryName=''
        return categoryName


    def __str__(self):
        return 'Nom: {0}'.format(self.name)


#=========================Commandes==================================================
class Order(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, verbose_name='Client', null=True, blank=True)
    ordered_at = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True)

    class Meta:
        verbose_name_plural = 'Commandes'
        ordering = ('-ordered_at',)
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_item(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.qty for item in orderitems])
        return total
        
    def __str__(self):
        return 'Commande Numéro {0}'.format(str(self.id))

#=====================OrderItem=========================================================
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,verbose_name='Produit',blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, verbose_name='Commande',blank=True, null=True)
    qty = models.IntegerField(default=0, verbose_name="Quantité", blank=True, null=True)
    ordered_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Eléments de commande'
        verbose_name = 'Elément de commande'
    @property
    def get_total(self):
        total = self.product.price * self.qty
        return total
    

    def __str__(self):

        return ' {0} {1} par: {2} '.format(str(self.qty), self.product.name, self.order.profile)

#===========================Adresse de livraison============================================
class ShippingAddress(models.Model):
    """docstring for ShippingAdress"""
    profile=models.ForeignKey(
        Profile, verbose_name= _('Adresse_de_livraison') , on_delete=models.SET_NULL , null=True)
    order=models.ForeignKey(
        Order, on_delete=models.CASCADE, verbose_name='Commande liée', blank=True, null=True)
    address=models.CharField(max_length=200, null=True)
    city=models.CharField(max_length=200, null=True)
    state=models.CharField(max_length=200, null=True)
    zipcode=models.CharField(max_length=200, null=True)
    ordered_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='Adresse de livraison'
        ordering=('-ordered_at',)

    def __str__(self):
        return '{0}: {1} {2}, {3}'.format(self.profile, self.address,self.city,self.state)

store/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms.widgets import PasswordInput, TextInput

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=TextInput(
            attrs={'placeholder':'Username',
            'class':'form-control'
            }
         ))
    password=forms.CharField(
        widget=PasswordInput(
            attrs={'placeholder':'Mot de passe',
            'class':'form-control'
            }
        ))
    class Meta:
        model = User
        fields = ('username', 'password')

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control"
            }
        ))
    first_name = forms.CharField(
        widget=TextInput(attrs={
            'placeholder':'Prenom',
            'class':'form-control'
            }
        ))
    last_name = forms.CharField(
        widget=TextInput(attrs={
            'placeholder':'Nom',
            'class':'form-control'
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Mot de passe",                
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Vérification mot de passe",                
                "class": "form-control"
            }
        ))

    class Meta: 
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

store/views.py
from profiles.models import Profile
from django.contrib.auth.models import User
from django.core import exceptions
from django.db.models.expressions import Exists
from .forms import LoginForm, SignUpForm
from django.core.checks import messages
from store.models import Category, Order, OrderItem, Product
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
# ============================And of importspro=========================


# =================Login View========================================
# def login_view(request):
#     if request.user.is_authenticated:
#         logout(request)
#     form = LoginForm(request.POST)
#     if request.method == 'POST':
#         username = request.POST.get('email')
#         password = request.POST.get('password')
#         user = authenticate(request, username = username, password = password)
#         #user = User.objects.get(username = username)
#         if user is not None:
#             login(request, user)
#             return redirect('store:index')
#     return render(request, 'store/login.html')
# def loginView(request):
#     if request.user.is_authenticated:
#         return redirect('store:profile')
#     else:
#         form = LoginForm(request.POST)
#         msg = None
#         if not request.user.is_authenticated:
#             if request.method == 'POST':
#                 if form.is_valid():
#                     username = form.cleaned_data.get('username')
#                     password = form.cleaned_data.get('password')
#                     profile = authenticate(username=username, password=password)
#                     if profile is not None:
#                         login(request, profile)
#                         return redirect('profile:profile')
#                     else:
#                             msg = 'Infos invalides'

#                 else:
#                     msg = 'Vérifier vos informtions'
#         else:
#             return redirect('store:index')

#     return render(request, 'store/login.html', {'form': form, 'msg': msg})


# ==============================SingUp====================================
def registerUser(request):

    msg = None
    success = False

    if request.method == "POST":
        
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            #msg = 'Compte crée avec succés  <a href="/login">Se connecter</a>.'
            success = True
            return redirect('store:index')
        else:
            msg = 'Formulaire invalide'
    else:
        form = SignUpForm()

    return render(request, "store/register.html", {"form": form, "msg": msg, "success": success})

# ===================Logout================================================


# =========================Home Page view============================


def index(request):

    # affiche tous les produits sur la page d'accueil
    if request.user.is_authenticated:
        return redirect('profile:profile')
    else:
        products = Product.objects.all()
        context = {'products': products}
    return render(request, 'store/index.html', context)

# =========================Peoduct Detail view===============


def productDetail(request,*args, **kwargs):
    product = Product.objects.get(id=kwargs.get('id'))

    context = {'product': product, }
    return render(request, 'store/product-detail.html', context)

# ========================Cart view===========================


def cart(request):
    
    if request.user.is_authenticated:
        profile=request.user.profile
        order, created = Order.objects.get_or_create(profile=profile, complete=False )
        items = order.orderitem_set.all()
    else:
        items=[]
        order ={'get_cart_total':0, 'get_cart_item':0}
    context = {'items':items, 'order':order}

    return render(request, 'store/cart.html', context)


# ========================Checkout view=======================
def checkout(request):
    
    if request.user.is_authenticated:
        profile = request.user.profile
        order, created = Order.objects.get_or_create(profile=profile, complete=False )
        items = order.orderitem_set.all()
    else:
        session = request.session
        items=[]
        order ={'get_cart_total':0, 'get_cart_item':0}
    context = {'items':items, 'order':order}
    return render(request, 'store/checkout.html', context)


# =====================Profile view==========================




def category(request):
    category = Category.objects.all()
    context = {'category': category}
    return render(request, 'store/category.html', context)

templates/store/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <title>{% block title %}{% endblock title %}</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href=" {% static 'store/dist/css/bootstrap.min.css' %} ">
   <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> -->
  <link rel="stylesheet" href=" {% static 'store/css/base.css' %} "> 
  {% block css %} {% endblock css %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'store:index' %}"><a href="/" class="logo  "><img class="rounded" height="32" width="auto" src="{% static 'store/img/gs21ultra.png' %}" alt=""></a></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05"
        aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'store:index' %}">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Produits</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href=" {% url 'store:category' %} ">Catégories</a>
          </li>
        </ul>
        <div id="login" class="form-inline my-2 my-lg-0">
          <a href="{% url 'login' %}" class="btnblock btn btn-info  btn-success  btn-block">Se
            connecter</a>
          <a href=" {% url 'store:register' %} " class="btnblock btn btn-info  btn-success  btn-block">S'inscrire</a>
        </div>
        <div class="form-inline my-2 my-lg-0">
          <a href="{% url 'store:cart' %}">
            <img id="cart-icon" src="{% static 'store/img/cart-icon.png' %}" height="auto" width="170">
          </a>
          <a href="{% url 'store:cart' %}">
            <p id="cart-total">3</p>
          </a>
        </div>
      </div>
    </div>
  </nav>
  {% block content %}

  {% endblock content %}
 
  <script src=" {% static 'store/dist/js/bootstrap.min.js' %} "></script>
</body>

</html>

templates/store/cart.html
{% extends './base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'store/css/cart.css' %}">{% endblock css %}
{% block title %}Mon panier{% endblock %}

{% block content %}
<div class="container">
    <div class="row" background-color="grey">
        <div class="col-md-12">
            <a href=" {% url 'store:index' %} "><button class="btn btn-outline-dark"><span>&#10096;</span>
                    Retour</button></a>
        </div>
        <div class="col-md-12 tb">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Nom</th>
                        <th scope="col">prix</th>
                        <th scope="col">Quantité</th>
                        <th scope="col">Sous-total</th>
                    </tr>
                </thead>
                {% if msg %}
                <div class="txt-warining">
                    <h3>{{msg|safe}}</h3>
                </div>
                {% else %}
                {% for item in items %}
                <tbody>
                    <tr>
                        <th scope="row"> <img class="rounded" height="45" width="auto" src="{{item.product.imageURL}}"
                                alt="">
                        </th>
                        <td>{{item.product.name}}</td>
                        <td>{{item.product.price}}</td>
                        <td>
                            <div class="arrow">
                                <div class="item"><b>{{item.qty}}</b></div>
                                <div>
                                    <img class="img-arrow" id="arrow-up" height="13px" width="auto"
                                        src=" {% static 'store/img/arrow-up.png' %} " alt="">
                                    <img class="img-arrow" id="arrow-down" height="13px" width="auto"
                                        src=" {% static 'store/img/arrow-down.png' %} " alt="">
                                </div>
                            </div>

                        </td>
                        <td>{{item.get_total}} Fcfa</td>
                    </tr>

                </tbody>
                {% endfor %}
                {%endif%}
                <tfoot>
                    <div class="total">
                        <h4>Total:</h4>

                        <h5></h5>{% if msg %} Total = 0 Fcfa {% else %} {{order.get_cart_total}}Fcfa {%endif%}</h5>
                    </div>
                </tfoot>
            </table>
            <a href="{% url 'store:checkout' %}">
                <button class="process-btn btn btn-success btn-block">Procéder au
                    paiement</button>
            </a>
        </div>
    </div>
</div>
{% endblock content %}

templates/store/category.html
{% extends './base.html' %}
{% load static %}
{% block css %}{% endblock css %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        {% for c in category %}
        <div class="col-md-4 rounded">
            <p><img {% if c.imageURL %} src=" {{c.imageURL}}" {% else %}src={% static 'store/img/dkandroid.png' %}{%endif%}  width='auto' height="250px" alt=" {{c.name}} "></a></p>
            <p>{{c.name}}</p>
            <a href=" {% url 'store:category' %} ">Voir la categorie</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/store/checkout.html
{% extends './base.html' %}
{% load static %}
{% block title %}Procéder au paiement{% endblock title %}
{% block content %}

<div class="container">
    <div class="row">
        <!-- <div class="col-md-12">
            <a href=" {% url 'store:index' %} "></a> <button style="float: left; margin-top: 10px; margin-bottom: 10px;"
                class="btn btn-outline-dark"><span>&#10096;</span> Retour au panier</button>
        </div> -->
        
        <div class="col-md-6" style="background-color: grey; margin-top: 10px; border-radius: 10px; ">
            <div style="display: inline-block;"> <a style="text-decoration: none;"
                    href=" {% url 'store:cart' %} "><button style="float: left; margin-top: 10px; margin-bottom: 10px;"
                        class="btn btn-outline-dark"><span>&#10096;</span> Retour au panier</button></a>
            </div>
            <p>Résumé du panier</p>
            <table class="table" style="text-align: center;">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Prix</th>
                        <th scope="col">Quantité</th>
                        <th scope="col">Sous total</th>
                    </tr>
                </thead>
                {% for item in items %}
                <tbody>
                    <tr>
                        <td>
                            <img class="rounded" src="{{item.product.imageURL}} " height="50px"
                                width="auto" alt="">
                        </td>
                        <td>{{item.product.price}}Fcfa</td>
                        <td style="text-align: center;">

                            <div style="display: inline-flex;">
                                <div style="display: block; margin-right:8px "><b>{{item.qty}}</b></div>
                                <div>
                                    <img style="display: block;" src=" {% static 'store/img/arrow-up.png' %} "
                                        height="13" width="auto" alt="">
                                    <img style="display: block;" src=" {% static 'store/img/arrow-down.png' %} "
                                        height="13" width="auto" alt="">
                                </div>
                            </div>

                        </td>
                        <td>{{item.get_total}}Fcfa</td>
                    </tr>
                </tbody>
                {% endfor %}
                <div style="float: right; display:inline-flex; margin-top: 10px;">
                    <h4 style="margin-top: -5px;">Total:</h4>
                    <h5 style="margin-left: 10px;">{{order.get_cart_total}}Fcfa</h5>
                </div>
            </table>

            </p>
        </div>
        <div class="col-md-6">
            <form>
                <div class="form-field">
                    <div class="form-field">
                        <input style="margin-bottom: 5px;margin-top: 10px;" class="form-control" type="text" name="name"
                            placeholder="Nom">
                    </div>
                    <div class="form-field"></div>
                    <input class="form-control" type="email" name="email" placeholder="Email">
                </div>
                <hr>
                <div id="shipping-info">
                    <p>Information de livraison</p>
                    <div class="form-field">
                        <input style="margin-bottom: 5px;" class="form-control" type="text" name="address"
                            placeholder="Adresse">
                    </div>
                    <div class="form-field">
                        <input style="margin-bottom: 5px;" class="form-control" type="text" name="city"
                            placeholder="Ville">
                    </div>
                    <div class="form-field">
                        <input style="margin-bottom: 5px;" class="form-control" type="text" name="state"
                            placeholder="Etat">
                    </div>
                    <div class="form-field">
                        <input style="margin-bottom: 5px;" class="form-control" type="text" name="zipcode"
                            placeholder="Code Postale">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="country" placeholder="Pays">
                    </div>

                </div>
                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="continuer">
            </form>

        </div>

    </div>

    {% endblock content %}

templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'store/css/index.css' %}">{% endblock css %}
{% block title %}Accueil|DeliaShop{% endblock title %}


{% block content %}

<div class="container-fluid">
    <div class="row">
        {% for product in products %}
        <div class=" product-detail col-md-3 col-sm-6 rounded" >
        <div class="   "><a href="{% url 'store:product-detail' product.id  %}"><img class="product-image" class="img-fluid rounded" src=" {{product.imageURL}} " alt=""></a></div>
            <div class="box-element">
                <a href="{% url 'store:product-detail' product.id %}"><h6><b>{{product.name}}</b></h6></a>
                <h6><b>{{product.price}} Fcfa</b></h6>
               <a class=" add btn btn-outline-dark " href="#">Ajouter au panier</a>
                <button class=" add btn btn-outline-info"><a href="{% url 'store:product-detail' product.id %}">Voir</a></button>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock content %}

templates/store/product-detail.html
{% extends './base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href=" {% static 'store/css/product_detail.css' %} "> {% endblock css %}
{% block title %}Detail{% endblock title %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid rounded" src=" {{product.imageURL}} " alt=" {{product.name}} ">
        </div>

        <div class="col-md-6 text-sm-center text-md-start ">
            <p class="card-title">
            <h4><span class=" btn-dark rounded d-block text-center ">{{product.name}}</span></h4>
            </p>
            <p class="card-title"><b>Prix: </b><span><b>{{product.price}} Fcfa</b></span> au lieu
                de <span style="padding-left:10px; ; color: red;"><b><strike style="font-size: xx-large;">{{product.oldPrice}} Fcfa</strike></b></span></p>
            </a><button class="btn btn-outline-success">Ajouter au panier</button>
            <hr>
            <article style="color: dark;" class=""> <span class=" btn-dark rounded d-block text-center ">
                    <h4>Description</h4>
                </span> {{product.description}} </article>
        </div>
    </div>
</div>
{% endblock content %}

templates/store/register.html
{% extends './base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'store/css/register.css' %}"> {% endblock css %}
{% block title %}Créer un compte{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-4  rounded "
        style="margin-left: 420px; margin-top:2%; ">
        <div class="card">
            <form role="form" method="post" action="">
                {% csrf_token %}
                <div class="card-header">
                    <h5 class="title">Inscription</h5>

                    <h6 class="card-category">
                        {% if msg %}
                        <span class="text-success">{{ msg | safe }}</span>
                        {% else %}
                        Ajouter vos informations
                        {% endif %}
                    </h6>
                </div>

                {% if success %}

                <p>
                    Veuillez vous <a href="{% url 'login' %}">connecter</a> en utilisant ce nouveau compte.
                </p>

                {% else %}

                <div class="card-body">

                    <div class="row">
                        <div class="col-md-6 px-md-1">
                            <div class="form-group">
                                <label></label>
                                {{ form.username }}
                            </div>
                            <span class="text-danger"><small style="font-size: 10px;">{{ form.username.errors }}</small></span>
                        </div>

                        <div class="col-md-6 px-md-1">
                            <div class="form-group">
                                <label></label>
                                {{ form.email }}
                            </div>
                            <div><span class="text-danger"><small>{{ form.email.errors }}</small></span></div>
                        </div>
                        

                    </div>
                    <div class="row">
                        <div class="col-md-6 px-md-1">
                            <div class="form-group">
                                <label></label>
                                {{ form.first_name }}
                            </div>
                            <div><span class=" text-danger"><small>{{ form.first_name.errors }}</small></span></div>
                        </div>

                        <div class="col-md-6 px-md-1">
                            <div class="form-group">
                                <label></label>
                                {{ form.last_name }}
                            </div>
                            <div> <span class="text-danger"><small>{{ form.last_name.errors }}</small></span></div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-6 px-md-1">
                            <div class="form-group">
                                <label></label>
                                {{ form.password1 }}
                            </div>
                            <div><span class="text-danger"><small>{{ form.password1.errors }}</small></span></div>

                        </div>
                        
                        <div class="col-md-6 px-md-1">
                            <div class="form-group">
                                <label></label>
                                {{ form.password2 }}
                            </div>
                            <div><span class="text-danger"><small style="font-size: small;" >{{ form.password2.errors }}</small></span></div>
                        </div>
                       
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" name="register" class="btn  btn-outline-info">M'inscrire</button>
                    &nbsp; &nbsp;
                    Déjà inscrit ? <a href="{% url 'login' %}" class="text-info">Se connecter</a>
                </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}